'use client';

import { useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import DOMPurify from 'dompurify';

interface GeneratedContent {
  title: string;
  content: string;
  format: 'html' | 'markdown';
  provider: string;
  timestamp: Date;
}

/**
 * Content Publishing Dashboard
 * Generate AI content and publish to Ghost CMS
 */
export default function PublishPage() {
  const [step, setStep] = useState<'generate' | 'preview' | 'publish'>('generate');
  const [generatedContent, setGeneratedContent] = useState<GeneratedContent | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  const [publishResult, setPublishResult] = useState<{ success: boolean; url?: string; error?: string } | null>(null);
  
  // Generation form state
  const [prompt, setPrompt] = useState('');
  const [contentType, setContentType] = useState<'blog' | 'ad' | 'social'>('blog');
  const [provider, setProvider] = useState<'openai' | 'github-models'>('openai');
  
  // Publishing options
  const [publishStatus, setPublishStatus] = useState<'draft' | 'published'>('draft');
  const [featured, setFeatured] = useState(false);
  const [tags, setTags] = useState<string[]>([]);
  const [tagInput, setTagInput] = useState('');

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    try {
      // Simulate AI generation (in real implementation, call your AI API)
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const content: GeneratedContent = {
        title: `Generated ${contentType} content`,
        content: contentType === 'blog' 
          ? `<h1>${prompt}</h1>\n\n<p>This is AI-generated blog content based on your prompt: "${prompt}".</p>\n\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n\n<h2>Key Points</h2>\n<ul>\n<li>Point 1: AI-powered content generation</li>\n<li>Point 2: Seamless Ghost integration</li>\n<li>Point 3: Professional publishing workflow</li>\n</ul>`
          : `<h2>${prompt}</h2>\n<p>Engaging ${contentType} copy generated by AI.</p>`,
        format: 'html',
        provider,
        timestamp: new Date()
      };
      
      setGeneratedContent(content);
      setStep('preview');
    } catch (error: any) {
      alert('Failed to generate content: ' + error.message);
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePublish = async () => {
    if (!generatedContent) return;

    setIsPublishing(true);
    setPublishResult(null);

    try {
      const response = await fetch('/api/ghost/publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          config: {
            url: process.env.NEXT_PUBLIC_GHOST_URL || '',
            contentApiKey: process.env.NEXT_PUBLIC_GHOST_CONTENT_API_KEY || '',
            adminApiKey: process.env.NEXT_PUBLIC_GHOST_ADMIN_API_KEY || ''
          },
          content: generatedContent,
          options: {
            status: publishStatus,
            featured,
            tags,
            addAIMetadata: true
          }
        })
      });

      const result = await response.json();
      
      if (result.success) {
        setPublishResult({
          success: true,
          url: result.postUrl
        });
        setStep('publish');
      } else {
        setPublishResult({
          success: false,
          error: result.error || 'Failed to publish'
        });
      }
    } catch (error: any) {
      setPublishResult({
        success: false,
        error: error.message || 'Network error'
      });
    } finally {
      setIsPublishing(false);
    }
  };

  const addTag = () => {
    if (tagInput.trim() && !tags.includes(tagInput.trim())) {
      setTags([...tags, tagInput.trim()]);
      setTagInput('');
    }
  };

  const removeTag = (tag: string) => {
    setTags(tags.filter(t => t !== tag));
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 p-8">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
            Content Publisher
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Generate AI content and publish to Ghost CMS
          </p>
        </div>

        {/* Step Indicator */}
        <div className="flex items-center justify-center mb-8 gap-4">
          <div className={`flex items-center gap-2 ${step === 'generate' ? 'text-blue-600' : 'text-gray-400'}`}>
            <div className={`w-8 h-8 rounded-full flex items-center justify-center ${step === 'generate' ? 'bg-blue-600 text-white' : 'bg-gray-200'}`}>
              1
            </div>
            <span className="font-medium">Generate</span>
          </div>
          <div className="w-16 h-1 bg-gray-200"></div>
          <div className={`flex items-center gap-2 ${step === 'preview' ? 'text-blue-600' : 'text-gray-400'}`}>
            <div className={`w-8 h-8 rounded-full flex items-center justify-center ${step === 'preview' ? 'bg-blue-600 text-white' : 'bg-gray-200'}`}>
              2
            </div>
            <span className="font-medium">Preview</span>
          </div>
          <div className="w-16 h-1 bg-gray-200"></div>
          <div className={`flex items-center gap-2 ${step === 'publish' ? 'text-blue-600' : 'text-gray-400'}`}>
            <div className={`w-8 h-8 rounded-full flex items-center justify-center ${step === 'publish' ? 'bg-blue-600 text-white' : 'bg-gray-200'}`}>
              3
            </div>
            <span className="font-medium">Publish</span>
          </div>
        </div>

        {/* Generate Step */}
        {step === 'generate' && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8"
          >
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-6">
              Generate Content
            </h2>

            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Content Type
                </label>
                <div className="flex gap-3">
                  {(['blog', 'ad', 'social'] as const).map((type) => (
                    <button
                      key={type}
                      onClick={() => setContentType(type)}
                      className={`flex-1 px-4 py-3 rounded-lg border-2 transition-all ${
                        contentType === type
                          ? 'border-blue-600 bg-blue-50 dark:bg-blue-900/20 text-blue-600'
                          : 'border-gray-300 dark:border-gray-600 hover:border-gray-400'
                      }`}
                    >
                      <span className="font-medium capitalize">{type} Post</span>
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  AI Provider
                </label>
                <select
                  value={provider}
                  onChange={(e) => setProvider(e.target.value as any)}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                >
                  <option value="openai">OpenAI GPT-4</option>
                  <option value="github-models">GitHub Models</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Content Prompt
                </label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="Enter your content prompt here..."
                  rows={6}
                  className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <button
                onClick={handleGenerate}
                disabled={isGenerating || !prompt.trim()}
                className="w-full px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white rounded-lg font-medium transition-colors"
              >
                {isGenerating ? 'Generating...' : 'Generate Content'}
              </button>
            </div>
          </motion.div>
        )}

        {/* Preview Step */}
        {step === 'preview' && generatedContent && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6"
          >
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-6">
                Preview Content
              </h2>
              
              <div className="prose dark:prose-invert max-w-none">
                <ContentPreview content={generatedContent.content} />
              </div>

              <div className="mt-6 pt-6 border-t border-gray-200 dark:border-gray-700">
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Generated by {generatedContent.provider} on {generatedContent.timestamp.toLocaleString()}
                </p>
              </div>
            </div>

            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-6">
                Publishing Options
              </h2>

              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Publish Status
                  </label>
                  <div className="flex gap-3">
                    <button
                      onClick={() => setPublishStatus('draft')}
                      className={`flex-1 px-4 py-2 rounded-lg border-2 transition-all ${
                        publishStatus === 'draft'
                          ? 'border-blue-600 bg-blue-50 dark:bg-blue-900/20 text-blue-600'
                          : 'border-gray-300 dark:border-gray-600'
                      }`}
                    >
                      Draft
                    </button>
                    <button
                      onClick={() => setPublishStatus('published')}
                      className={`flex-1 px-4 py-2 rounded-lg border-2 transition-all ${
                        publishStatus === 'published'
                          ? 'border-blue-600 bg-blue-50 dark:bg-blue-900/20 text-blue-600'
                          : 'border-gray-300 dark:border-gray-600'
                      }`}
                    >
                      Published
                    </button>
                  </div>
                </div>

                <div>
                  <label className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={featured}
                      onChange={(e) => setFeatured(e.target.checked)}
                      className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
                    />
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                      Mark as featured post
                    </span>
                  </label>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Tags
                  </label>
                  <div className="flex gap-2 mb-2">
                    <input
                      type="text"
                      value={tagInput}
                      onChange={(e) => setTagInput(e.target.value)}
                      onKeyPress={(e) => e.key === 'Enter' && addTag()}
                      placeholder="Add tag..."
                      className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                    />
                    <button
                      onClick={addTag}
                      className="px-4 py-2 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-white rounded-lg transition-colors"
                    >
                      Add
                    </button>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {tags.map((tag) => (
                      <span
                        key={tag}
                        className="px-3 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-800 dark:text-blue-200 rounded-full text-sm flex items-center gap-2"
                      >
                        {tag}
                        <button
                          onClick={() => removeTag(tag)}
                          className="hover:text-red-600"
                        >
                          ×
                        </button>
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {publishResult && !publishResult.success && (
                <div className="mt-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
                  <p className="text-red-800 dark:text-red-200">{publishResult.error}</p>
                </div>
              )}

              <div className="mt-6 flex gap-3">
                <button
                  onClick={() => setStep('generate')}
                  className="flex-1 px-6 py-3 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-white rounded-lg font-medium transition-colors"
                >
                  Back to Edit
                </button>
                <button
                  onClick={handlePublish}
                  disabled={isPublishing}
                  className="flex-1 px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white rounded-lg font-medium transition-colors"
                >
                  {isPublishing ? 'Publishing...' : 'Publish to Ghost'}
                </button>
              </div>
            </div>
          </motion.div>
        )}

        {/* Publish Success Step */}
        {step === 'publish' && publishResult?.success && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8 text-center"
          >
            <div className="w-16 h-16 bg-green-100 dark:bg-green-900/20 rounded-full flex items-center justify-center mx-auto mb-6">
              <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
              Published Successfully!
            </h2>
            <p className="text-gray-600 dark:text-gray-400 mb-6">
              Your content has been published to Ghost CMS
            </p>

            <div className="flex gap-3 justify-center">
              <a
                href={publishResult.url}
                target="_blank"
                rel="noopener noreferrer"
                className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors"
              >
                View on Ghost
              </a>
              <button
                onClick={() => {
                  setStep('generate');
                  setGeneratedContent(null);
                  setPublishResult(null);
                  setPrompt('');
                  setTags([]);
                }}
                className="px-6 py-3 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-white rounded-lg font-medium transition-colors"
              >
                Create Another
              </button>
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
}

/**
 * ContentPreview component that sanitizes HTML before rendering
 * to prevent XSS attacks
 */
function ContentPreview({ content }: { content: string }) {
  const sanitizedContent = useMemo(() => {
    // Only sanitize on the client side
    if (typeof window !== 'undefined') {
      // DOMPurify sanitization prevents XSS attacks by removing malicious scripts
      // and keeping only safe HTML elements and attributes
      return DOMPurify.sanitize(content, {
        ALLOWED_TAGS: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'a', 'ul', 'ol', 'li', 'strong', 'em', 'br', 'img', 'blockquote', 'code', 'pre'],
        ALLOWED_ATTR: ['href', 'src', 'alt', 'title', 'target', 'rel']
      });
    }
    return content;
  }, [content]);

  // Safe to use dangerouslySetInnerHTML here because content is sanitized by DOMPurify
  // which removes all potentially malicious scripts and attributes
  return <div dangerouslySetInnerHTML={{ __html: sanitizedContent }} />;
}
