PR-3: Providers:
  - "app/api/chat/**"
  - "lib/providers/**"
  - "docs/PROVIDER_INTEGRATION.md"
  - "docs/INTEGRATION_QUICKSTART.md"

PR-1: Supabase:
  - "lib/db/**"
  - "lib/supabase/**"
  - "app/dashboard/**"
  - "docs/DATABASE_SCHEMA.md"
  - "app/api/**"

PR-5: Auth:
  - "lib/auth/**"
  - "app/auth/**"
  - "app/**/layout.tsx"
  - "app/**/page.tsx"
  - "docs/INTEGRATION_QUICKSTART.md"
