# =====================================================
# AdGenXAI Netlify Configuration
# =====================================================

[build]
  # Build command
  command = "npm run build && npm run export"

  # Output directory
  publish = "out"

  # Node version
  environment = { NODE_VERSION = "18" }

# =====================================================
# Functions Configuration
# =====================================================

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["node_modules/**"]

# =====================================================
# Redirects for API Routes
# =====================================================

# Redirect /api/* to Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =====================================================
# Security Headers
# =====================================================

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/json"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# =====================================================
# Context-specific Settings
# =====================================================

[context.production]
  command = "npm run build && npm run export"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run build && npm run export"

# =====================================================
# Dev Settings
# =====================================================

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
