import { describe, it, expect } from "vitest";
import { POST } from "./route";

const makeRequest = (body: any) => {
  // Simulate NextRequest for POST handler
  return POST({
    json: async () => body,
    url: "http://localhost/api/campaign/orchestrate"
  } as any);
};

describe("Campaign Orchestration API", () => {
  it("returns a full campaign for a valid brief", async () => {
    const res = await makeRequest({ brief: "Launch a new AI product" });
    const data = await res.json();

    expect(res.status).toBe(200);
    expect(data.strategy).toContain("Strategy generated by");
    expect(data.image).toContain("Image generated by");
    expect(data.video).toContain("Video generated by");
    expect(data.audio).toContain("Audio generated by");
    expect(data.thumbnail).toContain("Thumbnail generated by");
    expect(data.providers).toBeTypeOf("object");
    expect(data.providers.kimi).toBeDefined();
    expect(data.providers.emu).toBeDefined();
    expect(data.providers.longcat).toBeDefined();
    expect(data.providers.ditto).toBeDefined();
    expect(data.providers.nitro).toBeDefined();
  });

  it("returns 400 for missing brief", async () => {
    const res = await makeRequest({});
    const data = await res.json();
    expect(res.status).toBe(400);
    expect(data.error).toMatch(/brief/i);
  });

  it("handles long briefs", async () => {
    const longBrief = "A".repeat(10000);
    const res = await makeRequest({ brief: longBrief });
    expect(res.status).toBe(200);
    const data = await res.json();
    expect(data.strategy).toContain("Strategy generated by");
  });
});
