import { FeedItem, GeneratedAd, Storyboard, SwarmStats } from '../types/beehive';

const API_BASE_URL = process.env.VITE_API_BASE_URL || 'http://localhost:3001/api';

class BeeHiveAPIClient {
  private baseURL: string;
  private headers: HeadersInit;

  constructor() {
    this.baseURL = API_BASE_URL;
    this.headers = {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    };
  }

  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<T> {
    const url = `${this.baseURL}${endpoint}`;
    const config: RequestInit = {
      ...options,
      headers: {
        ...this.headers,
        ...options.headers,
      },
    };

    try {
      const response = await fetch(url, config);
      
      if (!response.ok) {
        throw new Error(`API Error: ${response.status} ${response.statusText}`);
      }

      const data = await response.json();
      return data;
    } catch (error) {
      console.error(`API request failed for ${endpoint}:`, error);
      throw error;
    }
  }

  // SwarmFeed endpoints
  async getFeedItems(limit = 20, offset = 0): Promise<FeedItem[]> {
    return this.request<FeedItem[]>(`/swarm/feed?limit=${limit}&offset=${offset}`);
  }

  async getFeedItemById(id: string): Promise<FeedItem> {
    return this.request<FeedItem>(`/swarm/feed/${id}`);
  }

  async getSwarmStats(): Promise<SwarmStats> {
    return this.request<SwarmStats>('/swarm/stats');
  }

  // Ad generation endpoints
  async generateAd(request: {
    persona: string;
    productName: string;
    targetAudience: string;
    platform: string;
    tone?: string;
  }): Promise<GeneratedAd> {
    return this.request<GeneratedAd>('/generate/ad', {
      method: 'POST',
      body: JSON.stringify(request),
    });
  }

  async generateStoryboard(request: {
    persona: string;
    concept: string;
    duration: number;
    frames: number;
  }): Promise<Storyboard> {
    return this.request<Storyboard>('/generate/storyboard', {
      method: 'POST',
      body: JSON.stringify(request),
    });
  }

  // Creative history endpoints
  async getGeneratedAds(limit = 10): Promise<GeneratedAd[]> {
    return this.request<GeneratedAd[]>(`/creative/ads?limit=${limit}`);
  }

  async getStoryboards(limit = 10): Promise<Storyboard[]> {
    return this.request<Storyboard[]>(`/creative/storyboards?limit=${limit}`);
  }

  // Persona insights
  async getPersonaInsights(personaId: string): Promise<{
    totalUses: number;
    successRate: number;
    topPlatforms: string[];
    averageEngagement: number;
  }> {
    return this.request(`/personas/${personaId}/insights`);
  }

  // Real-time endpoints
  async subscribeToSwarmUpdates(callback: (item: FeedItem) => void): Promise<() => void> {
    // In a real implementation, this would establish a WebSocket connection
    // For now, we'll use polling
    const interval = setInterval(async () => {
      try {
        const items = await this.getFeedItems(1);
        if (items.length > 0) {
          callback(items[0]);
        }
      } catch (error) {
        console.error('Failed to fetch swarm updates:', error);
      }
    }, 5000);

    return () => clearInterval(interval);
  }
}

// Export singleton instance
export const apiClient = new BeeHiveAPIClient();

// Mock data generators for development
export const mockData = {
  generateFeedItem: (): FeedItem => {
    const types: FeedItem['type'][] = ['ad', 'storyboard', 'voice', 'sentiment'];
    const authors = ['SwarmMind', 'HiveCollective', 'CreativeNest', 'QuantumBee', 'NeuralHive'];
    const products = ['EcoSmart', 'UrbanFlow', 'MindSync', 'CloudNova', 'ZenTech', 'VitaBoost'];
    
    const type = types[Math.floor(Math.random() * types.length)];
    const author = authors[Math.floor(Math.random() * authors.length)];
    const product = products[Math.floor(Math.random() * products.length)];
    
    return {
      id: `feed-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      type,
      title: `${product} ${type === 'ad' ? 'Campaign' : type === 'storyboard' ? 'Story Arc' : type === 'voice' ? 'Voice Profile' : 'Sentiment Map'}`,
      description: `Generated by ${author} swarm intelligence for enhanced creative resonance`,
      timestamp: new Date(),
      swarmSize: Math.floor(Math.random() * 500) + 50,
      engagement: Math.random() * 100,
      author,
      tags: ['ai-generated', type, product.toLowerCase()],
    };
  },

  generateSwarmStats: (): SwarmStats => ({
    activeCreatives: Math.floor(Math.random() * 10000) + 5000,
    pulsingHives: Math.floor(Math.random() * 50) + 25,
    dailyOutputs: Math.floor(Math.random() * 1000) + 500,
    globalReach: Math.floor(Math.random() * 1000000) + 500000,
  }),

  generateAd: (): GeneratedAd => {
    const platforms = ['instagram', 'tiktok', 'youtube', 'linkedin', 'twitter'];
    const personas = ['bold', 'confident', 'clear', 'aspirational', 'inventor', 'urbanist'];
    const products = ['EcoSmart Phone', 'UrbanFlow Headphones', 'MindSync App', 'CloudNova Storage'];
    
    return {
      id: `ad-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      headline: `Transform Your World with ${products[Math.floor(Math.random() * products.length)]}`,
      copy: 'Experience the future of technology designed for the conscious consumer.',
      visualElements: ['product hero shot', 'lifestyle imagery', 'animated logo'],
      callToAction: 'Discover Innovation',
      platform: platforms[Math.floor(Math.random() * platforms.length)],
      persona: personas[Math.floor(Math.random() * personas.length)],
      timestamp: new Date(),
      engagement: {
        clicks: Math.floor(Math.random() * 5000),
        impressions: Math.floor(Math.random() * 50000),
        conversions: Math.floor(Math.random() * 500),
      },
    };
  },

  generateStoryboard: (): Storyboard => ({
    id: `story-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    title: 'Future Forward Brand Story',
    frames: [
      {
        id: 'frame-1',
        description: 'Opening with urban landscape at dawn',
        visualCues: 'golden hour lighting, city skyline',
        duration: 3,
      },
      {
        id: 'frame-2',
        description: 'Close-up of product in natural setting',
        visualCues: 'macro lens, soft focus background',
        duration: 4,
      },
      {
        id: 'frame-3',
        description: 'User interaction and transformation',
        visualCues: 'dynamic motion, energy particles',
        duration: 5,
      },
    ],
    totalDuration: 12,
    persona: 'aspirational',
    timestamp: new Date(),
  }),
};